version: "3.9"

services:
  fastapi:
    image: python:3.11
    working_dir: /app
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []