name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: raiosystems

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login no GCP com chave JSON
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configurar Docker para Artifact Registry
      run: |
        gcloud auth configure-docker

    - name: Build da imagem Docker
      run: |
        docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}-${{ github.ref_name }}:latest .
      working-directory: ./gcp_ingestao_cloudrun

    - name: Push da imagem Docker
      run: |
        docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}-${{ github.ref_name }}:latest
      working-directory: ./gcp_ingestao_cloudrun
